SELECT * FROM PIZZA_SALES;

-- KPI
-- 1. TOTAL REVENUE
SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES;
-- 2. TOTAL ORDERS
SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES;
-- 3. AVERAGE ORDER VALUE
SELECT CAST(CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) /
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS DECIMAL(10,2)) 
AS AVG_ORDER_VALUE
FROM PIZZA_SALES;
--4. TOTAL PIZZAS SOLD
SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM PIZZA_SALES;
--5. AVERAGE PIZZAS PER ORDER
SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL(10,2))/
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2))
AS DECIMAL(10,2)) AS AVG_PIZZA_PER_ORDER FROM PIZZA_SALES;



SELECT * FROM PIZZA_SALES;
--ANALYSIS
-- 1. Monthly Trend for Total Revenue
SELECT TO_CHAR(ORDER_DATE, 'MONTH') AS MONTH, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY TO_CHAR(ORDER_DATE, 'MONTH');
-- 2. Daily Trend for Total Orders
SELECT TO_CHAR(ORDER_DATE, 'DAY') AS DAY, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY TO_CHAR(ORDER_DATE, 'DAY');
--3. Percentage of Sales by Pizza Category
SELECT PIZZA_CATEGORY, SUM(TOTAL_PRICE) AS TOTAL_REVENUE,
CAST(SUM(TOTAL_PRICE)*100/ 
(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES) AS DECIMAL(10,2)) AS PCT
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;
--4.Percentage of Sales by Pizza Size
SELECT PIZZA_SIZE, SUM(TOTAL_PRICE) AS TOTAL_REVENUE,
CAST(SUM(TOTAL_PRICE)*100/ 
(SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES) AS DECIMAL(10,2)) AS PCT
FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;
-- 5.Total Pizzas Sold by Pizza Size and Category
SELECT PIZZA_SIZE,SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;
SELECT PIZZA_CATEGORY,SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;
-- 6. Revenue by Pizza Name
SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE ASC
LIMIT 5;

SELECT * FROM PIZZA_SALES;
-- Top & Bottom Analysis
-- 1. Top Pizza by Revenue
SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- 2. Bottom Pizza by Revenue
SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE 
LIMIT 5;

-- 3. Top Pizza by Orders
SELECT PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS DESC
LIMIT 5;

-- 4. Bottom Pizza by Orders
SELECT PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS 
LIMIT 5;

-- 5.Top Pizza by Quantity Sold
SELECT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY_SOLD DESC
LIMIT 5;

-- 6.Bottom Pizza by Quantity Sold
SELECT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY_SOLD ASC
LIMIT 5;